# Generated by Django 2.0 on 2019-12-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='ig_pic',
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Your username', max_length=50),
        ),
    ]
